### ISSUE TITLE
Some necessary files needed for reproduction

### ISSUE THREAD

**Issue by jiangxiluning** [facebookresearch/MultiplexedOCR#11]
Would you please provide Total_Text_ID_vs_ArT_ID.list and hindi_keep.list ? Thx.

**Comment by jiangxiluning** [comment]
I have found the Total_Text_ID_vs_ArT_ID.list but hindi_keep.list.

**Comment by SuperIRabbit** [comment]
Hi @jiangxiluning , 

I just uploaded hindi_keep.list : https://github.com/facebookresearch/MultiplexedOCR/blob/main/datasets/MLT19_Synthetic/Hindi_keep.list 

For reference of others, Total_Text_ID_vs_ArT_ID.list could be found in the github of Total Text dataset:
https://github.com/cs-chan/Total-Text-Dataset/blob/master/Total_Text_ID_vs_ArT_ID.list
