### ISSUE TITLE
Installation Requirements

### ISSUE THREAD

**Issue by leezx337** [facebookresearch/MultiplexedOCR#14]
Hello all,

May i check the specific version of python used in the creation of this programme? I have been trying to create the right environment for days to no avail due to dependency conflicts. TYIA!!

**Comment by SuperIRabbit** [comment]
Hi @leezx337 ,
The codebase should support python 3+
What kind of dependency conflicts are you seeing?

**Comment by leezx337** [comment]
Hello @SuperIRabbit , thank you for your prompt reply!! I'm sorry I just traced the errors and eventually found out that my GCC version is too high. The programme is created on CUDA 10.1 but my GCC version requires CUDA>11. Thank you once again for your reply!!
