### ISSUE TITLE
Request for Sharing the Weight Files

### ISSUE THREAD

**Issue by mobassir94** [facebookresearch/MultiplexedOCR#3]
Hi, 
thank you for this great OCR implementation sharing. i was waiting for this code to be released. i am trying to make this project working on rtx3090 where we can't use cudatoolkit=10.1. i tried this instead : conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch and everything else were same as these instructions : https://github.com/facebookresearch/MultiplexedOCR#requirements

during installation process i faced no error or warning.

`nvcc --version` says,

```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Sun_Feb_14_21:12:58_PST_2021
Cuda compilation tools, release 11.2, V11.2.152
Build cuda_11.2.r11.2/compiler.29618528_0
```

```

here in this section : https://github.com/facebookresearch/MultiplexedOCR#demo you have provided demo for running single image inference.ci don't see the weight files that can be used here : ` weight=YOUR_PATH_TO_WEIGHT_FILE` ,can you please share your trained weight files please? thanks in advance,great work <3

**Comment by SuperIRabbit** [comment]
Hi @mobassir94 , thank you for your interest! An example pretrained weights can be downloaded from [here](https://dl.fbaipublicfiles.com/MultiplexedOCR/weights/PMLX1G/PMLX1G.pth) now.
