### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by gtb1551050818** [facebookresearch/MultiplexedOCR#6]
Hello, thank you for your open source work. I want to reproduce your model. I want to see the effect of the model through the demo part. But I noticed that you didn't seem to provide the weight file. Can you provide the weight file? Thank you!

**Comment by SuperIRabbit** [comment]
Hi @gtb1551050818 , thank you for your interest! An example weights file can be downloaded from [here](https://github.com/facebookresearch/MultiplexedOCR#Models) now.
